import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/Nav/NavBar"

const outfit = Outfit({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
    >
      <body className={`${outfit.className} min-h-full flex flex-col`}>
        <NavBar/>
        {children}</body>
    </html>
  );
}
