import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/Nav/NavBar"
import { CartProvider } from "@/components/context/CartContext";

const outfit = Outfit({
  subsets: ["latin"],
});

export const metadata = {
  title: "Shopzee | An E Commerce Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en">
      <body className={`${outfit.className} min-h-full flex flex-col overflow-x-hidden`}>
        <CartProvider>
          <NavBar/>
        {children}
        </CartProvider>
        </body>
    </html>
  );
}
